#FROM pytorch/pytorch:2.5.0-cuda11.8-cudnn9-runtime
# FROM pytorch/pytorch:2.5.0-cuda12.4-cudnn9-devel
FROM pytorch/pytorch:2.6.0-cuda12.4-cudnn9-runtime


# install curl
RUN sed -i -e 's/http:\/\/archive\.ubuntu\.com\/ubuntu\//mirror:\/\/mirrors\.ubuntu\.com\/mirrors\.txt/' /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y curl

#RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
RUN pip3 install monai==1.4.0

# COPY ./weights/model_axial.pt /inpainting/weights/model_axial.pth
# COPY ./weights/model_coronal.pt /inpainting/weights/model_coronal.pth
# COPY ./weights/model_sagittal.pt /inpainting/weights/model_sagittal.pth

RUN mkdir -p /inpainting/weights && \
    curl https://zenodo.org/records/14510136/files/model_axial.pt -o /inpainting/weights/model_axial.pt && \
    curl https://zenodo.org/records/14510136/files/model_coronal.pt -o /inpainting/weights/model_coronal.pt && \
    curl https://zenodo.org/records/14510136/files/model_sagittal.pt -o /inpainting/weights/model_sagittal.pt

ENV INPAINTING_DIR=/inpainting

RUN mkdir -p /transformers_cache
ENV HF_HOME=/transformers_cache
RUN chmod -R a+w /transformers_cache

RUN mkdir -p /inpainting/.matplotlib
ENV MPLCONFIGDIR=/inpainting/.matplotlib
RUN chmod -R a+w /inpainting/.matplotlib

RUN mkdir -p /inpainting/.triton
ENV TRITON_CACHE_DIR=/inpainting/.triton
RUN chmod -R a+w /inpainting/.triton


RUN pip3 install matplotlib nibabel scipy

COPY run_lit.sh pyproject.toml git.hash /inpainting/
COPY lit /inpainting/lit



#WORKDIR /inpainting
ENTRYPOINT ["/bin/bash", "/inpainting/run_lit.sh"]

# clean up
RUN rm -rf /var/lib/apt/lists/*
RUN rm -rf /tmp/*
RUN rm -rf /var/tmp/*

